- name: install basic packages
  action: >
    {{ansible_pkg_mgr}} name={{ item }} state=present
  with_items:
    - tmux
    - vim
    - zsh
- name: Changing shell from bash to zsh
  command: chsh -s $(which zsh)
