---
- hosts: localhost
  roles:
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: defaults }
    - { role: docker, tags: ['docker']}
  vars:
    command_t_bundle: ext.so
    use_local_vim_dir: true
